apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: qwen-0-5b
  namespace: default
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    containers:
      - name: kserve-container
        image: vllm/vllm-openai:v0.6.3
        args:
          - "--model"
          - "Qwen/Qwen2.5-0.5B-Instruct"
          - "--max-model-len"
          - "512"
          - "--max-num-seqs"
          - "1"
          - "--dtype"
          - "bfloat16"
          - "--device"
          - "cpu"
          - "--swap-space"
          - "0"
          - "--enforce-eager"
          - "--port"
          - "8080"
        env:
          - name: VLLM_CPU_KVCACHE_SPACE
            value: "1"
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
        volumeMounts:
          - mountPath: /root/.cache/huggingface
            name: model-cache
    volumes:
      - name: model-cache
        hostPath:
          path: /model-cache
          type: DirectoryOrCreate