apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # grafana container reaches prometheus container by service name
    url: http://prometheus:9090
    isDefault: true
    access: proxy
